export function PageHeader({ eyebrow, title, description, action }) {
  return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.14em] text-brand">{eyebrow}</p><h1 className="text-[26px] font-semibold tracking-tight text-ink">{title}</h1>{description && <p className="mt-1.5 max-w-2xl text-sm text-muted">{description}</p>}</div>{action}</div>
}
export function Button({ children, variant = 'primary', icon: Icon, ...props }) { return <button className={`inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2.5 text-sm font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${variant === 'primary' ? 'bg-brand text-white shadow-sm hover:bg-[#106b65]' : variant === 'outline' ? 'border border-line bg-white text-ink hover:bg-slate-50' : 'text-muted hover:bg-slate-100'}`} {...props}>{Icon && <Icon size={16} strokeWidth={2} />}{children}</button> }
export function Badge({ children, tone = 'gray', dot = false }) { const tones = { gray: 'bg-slate-100 text-slate-600', green: 'bg-emerald-50 text-emerald-700', teal: 'bg-teal-50 text-teal-700', amber: 'bg-amber-50 text-amber-700', rose: 'bg-rose-50 text-rose-700', blue: 'bg-blue-50 text-blue-700', violet: 'bg-violet-50 text-violet-700' }; return <span className={`inline-flex w-fit items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium ${tones[tone] || tones.gray}`}>{dot && <span className="h-1.5 w-1.5 rounded-full bg-current" />}{children}</span> }
export function Card({ children, className = '' }) { return <section className={`rounded-xl border border-line bg-white shadow-panel ${className}`}>{children}</section> }
export function CardHeading({ title, subtitle, action }) { return <div className="flex items-start justify-between gap-3 px-5 pt-5"><div><h2 className="text-sm font-semibold text-ink">{title}</h2>{subtitle && <p className="mt-1 text-xs text-muted">{subtitle}</p>}</div>{action}</div> }
export function Avatar({ name, size = 'md' }) { const initials = name.split(' ').map((part) => part[0]).slice(0, 2).join(''); return <div className={`flex shrink-0 items-center justify-center rounded-full bg-[#e4f2ef] font-semibold text-[#16766e] ${size === 'sm' ? 'h-8 w-8 text-[11px]' : 'h-9 w-9 text-xs'}`}>{initials}</div> }
export function Input({ className = '', ...props }) { return <input className={`w-full rounded-lg border border-line bg-white px-3 py-2.5 text-sm text-ink outline-none placeholder:text-slate-400 focus:border-brand/50 focus:ring-2 focus:ring-brand/10 ${className}`} {...props} /> }
export function Select({ className = '', children, ...props }) { return <select className={`rounded-lg border border-line bg-white px-3 py-2.5 text-sm text-ink outline-none focus:border-brand/50 focus:ring-2 focus:ring-brand/10 ${className}`} {...props}>{children}</select> }
export function Table({ columns, rows, emptyMessage = 'Nothing to show yet.' }) { return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-y border-line bg-slate-50/80">{columns.map((column) => <th className="px-5 py-3 text-[11px] font-semibold uppercase tracking-wider text-muted" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr className="border-b border-line last:border-0 hover:bg-slate-50/60" key={row.id}>{columns.map((column) => <td className="px-5 py-4 text-sm text-slate-700" key={column.key}>{column.render ? column.render(row) : row[column.key]}</td>)}</tr>) : <tr><td colSpan={columns.length} className="px-5 py-12 text-center text-sm text-muted">{emptyMessage}</td></tr>}</tbody></table></div> }
export function MetricCard({ label, value, note, icon: Icon, tone = 'teal' }) { const toneClass = { teal: 'bg-teal-50 text-teal-700', blue: 'bg-blue-50 text-blue-700', violet: 'bg-violet-50 text-violet-700', amber: 'bg-amber-50 text-amber-700', rose: 'bg-rose-50 text-rose-700', green: 'bg-emerald-50 text-emerald-700' }[tone]; return <Card className="p-4"><div className="flex items-start justify-between"><div className="text-xs font-medium text-muted">{label}</div><span className={`rounded-lg p-2 ${toneClass}`}><Icon size={16} /></span></div><p className="mt-3 text-[25px] font-semibold tracking-tight text-ink">{value}</p><p className="mt-1 text-xs text-muted">{note}</p></Card> }
export function EmptyState({ title = 'No results found', description = 'Try adjusting your filters to find what you need.' }) { return <div className="flex min-h-48 flex-col items-center justify-center px-6 text-center"><div className="mb-3 rounded-full bg-slate-100 p-3 text-muted"><CircleHelp size={20} /></div><h3 className="text-sm font-semibold text-ink">{title}</h3><p className="mt-1 text-sm text-muted">{description}</p></div> }
export function LoadingState({ label = 'Loading…' }) { return <div className="flex min-h-40 items-center justify-center gap-3 text-sm text-muted"><span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-200 border-t-brand" />{label}</div> }
export function ErrorState({ message = 'Something went wrong. Please try again.' }) { return <div className="flex items-center gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><AlertCircle size={18} />{message}</div> }
export function SectionLabel({ children }) { return <p className="text-[11px] font-semibold uppercase tracking-[.13em] text-muted">{children}</p> }
