import { useCallback, useEffect, useState } from 'react'
import { CircleAlert, RefreshCw, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card, EmptyState, Input, LoadingState, PageHeader } from '../components/UI'
import { getApiErrorMessage, getSchedules, resolveConflict, schedulesApi } from '../services/api'

const localDate = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const today = new Date(), endDefault = new Date(today); endDefault.setDate(today.getDate() + 6)
const display = (value) => value == null ? '—' : String(value)

export default function Conflicts() {
  const [startDate, setStartDate] = useState(localDate(today)), [endDate, setEndDate] = useState(localDate(endDefault))
  const [schedules, setSchedules] = useState([]), [selectedSchedule, setSelectedSchedule] = useState('')
  const [result, setResult] = useState(null), [loading, setLoading] = useState(false), [initialLoading, setInitialLoading] = useState(true), [error, setError] = useState(''), [query, setQuery] = useState('')
  const loadSchedules = useCallback(async () => { setInitialLoading(true); try { const response = await getSchedules({ limit: 500 }); setSchedules(Array.isArray(response.data) ? response.data : []) } catch (e) { setError(getApiErrorMessage(e)) } finally { setInitialLoading(false) } }, [])
  useEffect(() => { loadSchedules() }, [loadSchedules])
  const analyze = async () => { setSelectedSchedule(''); setLoading(true); setError(''); setResult(null); try { setResult((await resolveConflict({ start_date: startDate, end_date: endDate })).data) } catch (e) { setError(getApiErrorMessage(e)) } finally { setLoading(false) } }
  const loadSaved = async (id) => { setSelectedSchedule(id); setResult(null); setError(''); if (!id) return; setLoading(true); try { const rows = (await schedulesApi.getConflicts(id)).data; setResult({ status: rows.length ? 'SAVED_CONFLICTS' : 'NO_SAVED_CONFLICTS', conflicts: rows || [], resolutions: [], source_schedule_id: id }) } catch (e) { setError(getApiErrorMessage(e)) } finally { setLoading(false) } }
  const conflicts = (result?.conflicts || []).filter((item) => `${item.type || ''} ${item.message || ''} ${item.skill || ''}`.toLowerCase().includes(query.toLowerCase()))
  const resolutions = result?.resolutions || []
  return <>
    <PageHeader eyebrow="Schedule health · Live API" title="Conflicts" description="Inspect persisted schedule conflicts or run the backend’s evidence-based infeasibility analyzer." action={<Link to="/schedule" className="rounded-lg border border-line bg-white px-3.5 py-2.5 text-sm font-semibold text-ink">Schedule planning</Link>}/>
    <Card className="mb-5 p-4"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-medium text-muted">Diagnostic start<Input className="mt-1" type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)}/></label><label className="text-xs font-medium text-muted">End date<Input className="mt-1" type="date" min={startDate} value={endDate} onChange={(e) => setEndDate(e.target.value)}/></label><Button icon={Search} disabled={loading || !startDate || !endDate || endDate < startDate} onClick={analyze}>{loading && !selectedSchedule ? 'Analyzing…' : 'Analyze date range'}</Button><span className="text-xs text-muted">Analysis is non-persistent; it does not alter workforce data.</span></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-line pt-4"><label htmlFor="saved-schedule" className="text-xs font-medium text-muted">Saved schedule conflicts</label><select id="saved-schedule" className="rounded-lg border border-line bg-white px-3 py-2 text-sm" value={selectedSchedule} onChange={(e) => loadSaved(e.target.value)}><option value="">Choose schedule</option>{schedules.map((item) => <option key={item.id} value={item.id}>{item.name || `Schedule #${item.id}`}</option>)}</select>{initialLoading && <span className="text-xs text-muted">Loading schedules…</span>}</div></Card>
    {error && <Card className="mb-5 p-4"><p role="alert" className="text-sm text-rose-700">{error}</p><Button className="mt-3" variant="outline" onClick={selectedSchedule ? () => loadSaved(selectedSchedule) : analyze}>Retry</Button></Card>}
    {loading && <Card className="mb-5"><LoadingState label={selectedSchedule ? 'Loading saved conflicts…' : 'Checking infeasibility and testing bounded candidate changes…'}/></Card>}
    {result && !loading && <>
      <Card className="mb-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className={`rounded-lg p-2 ${conflicts.length ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'}`}><CircleAlert size={18}/></span><div><h2 className="font-semibold text-ink">{result.status === 'ALREADY_FEASIBLE' ? 'Inputs are already feasible' : result.status === 'INFEASIBLE' ? 'Infeasibility diagnostics' : result.status === 'NO_SAVED_CONFLICTS' ? 'No conflicts recorded' : 'Saved schedule conflicts'}</h2><p className="mt-1 text-xs text-muted">{result.status === 'INFEASIBLE' ? 'Evidence-based diagnostics, not a formal mathematical proof.' : result.status === 'ALREADY_FEASIBLE' ? 'The optimizer found a feasible solution, so no repair proposals were generated.' : result.source_schedule_id ? `Loaded from schedule #${result.source_schedule_id}.` : `${conflicts.length} conflict records returned.`}</p></div></div><Badge tone={conflicts.length ? 'rose' : 'green'} dot>{conflicts.length} conflicts</Badge></div></Card>
      {conflicts.length > 0 ? <><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Conflict details</h2><Input aria-label="Filter conflicts" className="max-w-xs" placeholder="Filter type or message" value={query} onChange={(e) => setQuery(e.target.value)}/></div><div className="space-y-3">{conflicts.map((item, index) => <Card key={item.conflict_id || item.id || index} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone="rose">{item.type || 'Conflict'}</Badge>{item.severity && <Badge tone={item.severity === 'CRITICAL' ? 'rose' : 'amber'}>{item.severity}</Badge>}<span className="text-xs text-muted">{item.conflict_id || (item.id ? `Conflict #${item.id}` : '')}</span></div><h3 className="mt-3 text-sm font-semibold text-ink">{item.message || 'Conflict details unavailable'}</h3>{item.details && typeof item.details === 'string' && <p className="mt-1 text-sm text-muted">{item.details}</p>}<div className="mt-4 grid gap-3 rounded-lg bg-slate-50 p-3 sm:grid-cols-3">{[['Required', item.required], ['Available', item.available], ['Gap', item.gap]].map(([label, value]) => <div key={label}><p className="text-[11px] text-muted">{label}</p><p className="mt-1 text-sm font-semibold text-ink">{display(value)}</p></div>)}</div><div className="mt-3 flex flex-wrap gap-2">{item.shift_ids?.length > 0 && <Badge tone="gray">Shifts: {item.shift_ids.join(', ')}</Badge>}{item.shift_id != null && !item.shift_ids?.length && <Badge tone="gray">Shift: {item.shift_id}</Badge>}{item.employee_ids?.length > 0 && <Badge tone="gray">Employees: {item.employee_ids.join(', ')}</Badge>}{item.project_id != null && <Badge tone="gray">Project: {item.project_id}</Badge>}{item.requirement_id != null && <Badge tone="gray">Requirement: {item.requirement_id}</Badge>}{item.skill && <Badge tone="blue">Skill: {item.skill}</Badge>}{item.constraints?.map((constraint) => <Badge key={constraint} tone="gray">{constraint}</Badge>)}</div>{item.minimum_proficiency != null && <p className="mt-2 text-xs text-muted">Minimum proficiency: {item.minimum_proficiency}</p>}</Card>)}</div></> : <Card><EmptyState title={result.status === 'ALREADY_FEASIBLE' ? 'No repair needed' : 'No conflicts to display'} description="The selected result did not return conflict records."/></Card>}
      {result.status === 'INFEASIBLE' && <section className="mt-6"><h2 className="mb-1 text-base font-semibold text-ink">Tested resolution proposals</h2><p className="mb-4 text-xs text-muted">Only candidates tested by the backend optimizer are listed. No proposal has been applied to stored data.</p>{resolutions.length ? <div className="space-y-3">{resolutions.map((item) => <Card key={item.resolution_id} className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge tone={item.testable && item.feasible ? 'green' : 'amber'} dot>{item.testable && item.feasible ? 'FEASIBLE · VERIFIED' : 'INFORMATIONAL · NOT TESTABLE'}</Badge><Badge tone="gray">{item.type}</Badge><span className="text-xs text-muted">Change size {display(item.change_size)}</span></div><h3 className="mt-3 text-sm font-semibold text-ink">{item.description}</h3><div className="mt-3 flex flex-wrap gap-2">{(item.affected_shift_ids || []).map((id) => <Badge key={`s${id}`} tone="blue">Shift {id}</Badge>)}{(item.affected_employee_ids || []).map((id) => <Badge key={`e${id}`} tone="gray">Employee {id}</Badge>)}{(item.affected_project_ids || []).map((id) => <Badge key={`p${id}`} tone="violet">Project {id}</Badge>)}</div>{item.details && <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{JSON.stringify(item.details, null, 2)}</pre>}</Card>)}</div> : <Card><EmptyState title="No tested proposals returned" description="The analyzer did not find a tested candidate repair for these inputs."/></Card>}</section>}
    </>}
    {!result && !loading && !error && <Card><EmptyState title="No conflict results loaded" description="Analyze a date range or select a saved schedule to inspect backend conflict data."/></Card>}
  </>
}
