import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronDown, Clock3, MoreHorizontal, Sparkles, TriangleAlert, Users, IndianRupee, CalendarCheck, Heart } from 'lucide-react'
import { Badge, Button, Card, CardHeading, MetricCard, PageHeader } from '../components/UI'
import { costData, coverageData, hoursData, metrics, mixData } from '../data/mockData'
const metricIcons = { Users, CalendarCheck, IndianRupee, Clock3, TriangleAlert, Heart }
const COLORS = ['#168078', '#559fca', '#9b87d2', '#e5aa59']
const Tip = ({ active, payload, label }) => active && payload?.length ? <div className="rounded-lg border border-line bg-white px-3 py-2 text-xs shadow-lg"><p className="font-semibold text-ink">{label}</p><p className="mt-1 text-muted">{payload[0].name}: {payload[0].value}{payload[0].unit || ''}</p></div> : null
export default function Dashboard() {
 return <><PageHeader eyebrow="Overview · Week 41" title="Good morning, Aarav" description="Here’s what’s happening with your workforce this week." action={<div className="flex gap-2"><Button variant="outline" icon={CalendarDays}>6 – 12 Oct <ChevronDown size={14} /></Button><Button icon={Sparkles}>Create schedule</Button></div>} />
  <div className="mb-6 flex flex-wrap items-center gap-2"><Badge tone="green" dot>Planning period open</Badge><span className="text-xs text-muted">Last updated 9:42 AM · Figures are illustrative mock data</span></div>
  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{metrics.map((metric) => <MetricCard key={metric.label} {...metric} icon={metricIcons[metric.icon]} />)}</div>
  <div className="mt-6 grid grid-cols-1 gap-4 xl:grid-cols-5"><Card className="xl:col-span-3"><CardHeading title="Coverage by department" subtitle="Scheduled hours as a share of target" action={<button aria-label="More chart options" className="rounded p-1 text-muted hover:bg-slate-100"><MoreHorizontal size={18} /></button>} /><div className="h-[260px] px-3 pb-4 pt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={coverageData} margin={{ top: 10, right: 12, left: -18, bottom: 0 }} barCategoryGap="36%"><CartesianGrid vertical={false} stroke="#edf0f2" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#687884', fontSize: 11 }} tickMargin={12} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: '#96a2aa', fontSize: 10 }} tickFormatter={(v) => `${v}%`} /><Tooltip content={<Tip />} /><Bar dataKey="scheduled" name="Scheduled" fill="#168078" radius={[5, 5, 0, 0]} /><Bar dataKey="target" name="Target" fill="#e8eeed" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="flex gap-4 border-t border-line px-5 py-3 text-xs text-muted"><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-brand" />Scheduled</span><span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-slate-200" />Target</span></div></Card>
  <Card className="xl:col-span-2"><CardHeading title="Labor cost trend" subtitle="Daily cost · ₹ thousands" action={<button className="flex items-center gap-1 text-xs text-muted">This week <ChevronDown size={13} /></button>} /><div className="h-[260px] px-3 pb-5 pt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={costData} margin={{ top: 12, right: 12, left: -10, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0f2" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#687884', fontSize: 11 }} tickMargin={11} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#96a2aa', fontSize: 10 }} tickFormatter={(v) => `₹${v}k`} /><Tooltip content={<Tip />} /><Bar dataKey="cost" name="Cost" fill="#76b7ad" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></Card></div>
  <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-3"><Card><CardHeading title="Working hours" subtitle="Employees by weekly hours" /><div className="flex items-center gap-2 px-4 pb-3 pt-1"><div className="h-[195px] min-w-0 flex-1"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={hoursData} dataKey="value" nameKey="name" innerRadius={52} outerRadius={76} paddingAngle={3} stroke="none">{hoursData.map((entry, i) => <Cell key={entry.name} fill={COLORS[i]} />)}</Pie><Tooltip content={<Tip />} /></PieChart></ResponsiveContainer></div><div className="space-y-3 pr-2">{hoursData.map((entry, i) => <div key={entry.name} className="flex items-center gap-2 text-[11px] text-muted"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: COLORS[i] }} />{entry.name}<b className="ml-auto pl-2 font-semibold text-ink">{entry.value}</b></div>)}</div></div></Card><Card><CardHeading title="Shift distribution" subtitle="Across day, night and weekend" /><div className="flex items-center gap-2 px-4 pb-3 pt-1"><div className="h-[195px] min-w-0 flex-1"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={mixData} dataKey="value" nameKey="name" innerRadius={52} outerRadius={76} paddingAngle={3} stroke="none">{mixData.map((entry, i) => <Cell key={entry.name} fill={COLORS[i]} />)}</Pie><Tooltip content={<Tip />} /></PieChart></ResponsiveContainer></div><div className="space-y-3 pr-2">{mixData.map((entry, i) => <div key={entry.name} className="flex items-center gap-2 text-[11px] text-muted"><span className="h-2 w-2 shrink-0 rounded-full" style={{ background: COLORS[i] }} />{entry.name}<b className="ml-auto pl-2 font-semibold text-ink">{entry.value}%</b></div>)}</div></div></Card><Card><CardHeading title="Needs attention" action={<button className="text-xs font-medium text-brand">View all</button>} /><div className="divide-y divide-line px-5"><div className="flex gap-3 py-4"><span className="rounded-lg bg-rose-50 p-2 text-rose-700"><TriangleAlert size={16} /></span><div><p className="text-xs font-semibold text-ink">Night shift is understaffed</p><p className="mt-1 text-[11px] text-muted">7 Oct · Logistics · 2 people needed</p></div></div><div className="flex gap-3 py-4"><span className="rounded-lg bg-amber-50 p-2 text-amber-700"><Clock3 size={16} /></span><div><p className="text-xs font-semibold text-ink">Overtime threshold approaching</p><p className="mt-1 text-[11px] text-muted">3 employees near weekly limit</p></div></div><div className="flex gap-3 py-4"><span className="rounded-lg bg-blue-50 p-2 text-blue-700"><CalendarDays size={16} /></span><div><p className="text-xs font-semibold text-ink">Schedule draft ready to review</p><p className="mt-1 text-[11px] text-muted">Week of 6 October · updated 9:24 AM</p></div></div></div></Card></div>
 </>
}
