import { useMemo, useState } from 'react'
import { Download, MoreHorizontal, Plus, Search, SlidersHorizontal, Users } from 'lucide-react'
import { Avatar, Badge, Button, Card, Input, PageHeader, Select, Table } from '../components/UI'
import { departments, employees } from '../data/mockData'
export default function Employees() {
 const [query, setQuery] = useState(''), [department, setDepartment] = useState('All departments'), [status, setStatus] = useState('All status'), [selected, setSelected] = useState(null)
 const filtered = useMemo(() => employees.filter((employee) => `${employee.name} ${employee.code} ${employee.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (department === 'All departments' || employee.department === department) && (status === 'All status' || (status === 'Active' ? employee.active : !employee.active))), [query, department, status])
 const columns = [{ key: 'name', label: 'Employee', render: (row) => <button className="flex items-center gap-3 text-left" onClick={() => setSelected(row)}><Avatar name={row.name} /><span><span className="block font-semibold text-ink">{row.name}</span><span className="text-xs text-muted">{row.code}</span></span></button> }, { key: 'department', label: 'Department' }, { key: 'skills', label: 'Skills', render: (row) => <div className="flex gap-1.5">{row.skills.map((skill) => <Badge key={skill} tone="gray">{skill}</Badge>)}</div> }, { key: 'rate', label: 'Hourly rate', render: (row) => `₹${row.rate}/hr` }, { key: 'maxHours', label: 'Max hours', render: (row) => `${row.maxHours} hrs` }, { key: 'active', label: 'Status', render: (row) => <Badge tone={row.active ? 'green' : 'gray'} dot>{row.active ? 'Active' : 'Inactive'}</Badge> }, { key: 'actions', label: '', render: () => <button aria-label="More options" className="rounded p-1.5 text-muted hover:bg-slate-100"><MoreHorizontal size={17} /></button> }]
 return <><PageHeader eyebrow="People" title="Employees" description="Manage your people, skills and availability in one place." action={<div className="flex gap-2"><Button variant="outline" icon={Download}>Export</Button><Button icon={Plus}>Add employee</Button></div>} />
 <div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-3"><Card className="flex items-center gap-3 p-4"><span className="rounded-lg bg-teal-50 p-2.5 text-brand"><Users size={18}/></span><div><p className="text-xl font-semibold text-ink">48</p><p className="text-xs text-muted">Total employees</p></div></Card><Card className="flex items-center gap-3 p-4"><span className="rounded-lg bg-emerald-50 p-2.5 text-emerald-700"><Users size={18}/></span><div><p className="text-xl font-semibold text-ink">42</p><p className="text-xs text-muted">Active employees</p></div></Card><Card className="flex items-center gap-3 p-4"><span className="rounded-lg bg-blue-50 p-2.5 text-blue-700"><Users size={18}/></span><div><p className="text-xl font-semibold text-ink">3</p><p className="text-xs text-muted">Departments</p></div></Card></div>
 <Card><div className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="relative min-w-[220px] flex-1 sm:max-w-xs"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input className="pl-9" placeholder="Search name, code or skill" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="flex flex-wrap items-center gap-2"><Select value={department} onChange={(e) => setDepartment(e.target.value)}><option>All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</Select><Select value={status} onChange={(e) => setStatus(e.target.value)}><option>All status</option><option>Active</option><option>Inactive</option></Select><Button variant="outline" icon={SlidersHorizontal}>Filters</Button></div></div><Table columns={columns} rows={filtered} emptyMessage="No employees match those filters."/><div className="flex items-center justify-between border-t border-line px-5 py-3 text-xs text-muted"><span>Showing <b className="text-ink">{filtered.length}</b> of 48 employees · Mock data</span><div className="flex gap-2"><Button variant="outline">Previous</Button><Button variant="outline">Next</Button></div></div></Card>
 {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/25" onClick={() => setSelected(null)}><div onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-xl"><button onClick={() => setSelected(null)} className="float-right rounded-lg px-2 py-1 text-muted hover:bg-slate-100">×</button><p className="text-xs font-semibold uppercase tracking-wider text-brand">Employee profile · Mock data</p><div className="mt-6 flex items-center gap-4"><Avatar name={selected.name} /><div><h2 className="text-xl font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-muted">{selected.code} · {selected.department}</p></div></div><div className="mt-7 grid grid-cols-2 gap-3">{[['Hourly rate', `₹${selected.rate}`], ['Maximum hours', `${selected.maxHours} hrs`], ['Status', selected.active ? 'Active' : 'Inactive'], ['Department', selected.department]].map(([label, value]) => <div className="rounded-lg border border-line p-3" key={label}><p className="text-xs text-muted">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><h3 className="mb-2 mt-6 text-sm font-semibold">Skills</h3><div className="flex gap-2">{selected.skills.map((skill) => <Badge key={skill} tone="teal">{skill}</Badge>)}</div><p className="mt-8 text-xs text-muted">Profile actions are placeholders. Sample profile values are not connected to the backend.</p></div></div>}
 </>
}
