import { useCallback, useEffect, useState } from 'react'
import { CalendarDays, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { Badge, Button, Card, EmptyState, Input, LoadingState, PageHeader, Select } from '../components/UI'
import { getApiErrorMessage, getProjects, getSkills, projectsApi } from '../services/api'

const dateText = (value) => value ? new Date(`${String(value).slice(0, 10)}T12:00:00`).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : 'No deadline'

export default function Projects() {
  const [projects, setProjects] = useState([]), [skills, setSkills] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [showForm, setShowForm] = useState(false), [saving, setSaving] = useState(false), [formError, setFormError] = useState(''), [requirementFor, setRequirementFor] = useState(null)
  const [editingProject, setEditingProject] = useState(null)
  const [form, setForm] = useState({ name: '', status: 'planned', description: '', deadline: '' }), [requirement, setRequirement] = useState({ skill_id: '', role: 'staff', quantity: 1, required_hours: 0, minimum_proficiency: 1 })
  const load = useCallback(async () => {
    setLoading(true); setError('')
    try { const [projectResponse, skillResponse] = await Promise.all([getProjects({ limit: 500 }), getSkills({ limit: 500 })]); setProjects(Array.isArray(projectResponse.data) ? projectResponse.data : []); setSkills(Array.isArray(skillResponse.data) ? skillResponse.data : []) }
    catch (e) { setError(getApiErrorMessage(e)) } finally { setLoading(false) }
  }, [])
  useEffect(() => { load() }, [load])
  const create = async (event) => { event.preventDefault(); setSaving(true); setFormError(''); try { const payload = { ...form, deadline: form.deadline || null }; if (editingProject) await projectsApi.update(editingProject.id, payload); else await projectsApi.create(payload); setShowForm(false); setEditingProject(null); setForm({ name: '', status: 'planned', description: '', deadline: '' }); await load() } catch (e) { setFormError(getApiErrorMessage(e)) } finally { setSaving(false) } }
  const editProject = (project) => { setEditingProject(project); setFormError(''); setForm({ name: project.name, status: project.status || 'planned', description: project.description || '', deadline: project.deadline ? String(project.deadline).slice(0, 10) : '' }); setShowForm(true) }
  const addRequirement = async (event) => { event.preventDefault(); if (!requirementFor) return; setSaving(true); setFormError(''); try { await projectsApi.addRequirement(requirementFor.id, { ...requirement, skill_id: requirement.skill_id ? Number(requirement.skill_id) : null, quantity: Number(requirement.quantity), required_hours: Number(requirement.required_hours), minimum_proficiency: Number(requirement.minimum_proficiency) }); setRequirementFor(null); await load() } catch (e) { setFormError(getApiErrorMessage(e)) } finally { setSaving(false) } }
  const removeRequirement = async (projectId, item) => { if (!window.confirm(`Remove requirement “${item.role}” from this project?`)) return; try { await projectsApi.removeRequirement(projectId, item.id); await load() } catch (e) { setError(getApiErrorMessage(e)) } }
  const removeProject = async (item) => { if (!window.confirm(`Delete project “${item.name}”?`)) return; try { await projectsApi.remove(item.id); await load() } catch (e) { setError(getApiErrorMessage(e)) } }
  return <>
    <PageHeader eyebrow="Work planning · Live API" title="Projects" description="Manage project status, deadlines and optimizer requirements." action={<div className="flex gap-2"><Button variant="outline" icon={RefreshCw} onClick={load}>Refresh</Button><Button icon={Plus} onClick={() => { setEditingProject(null); setForm({ name: '', status: 'planned', description: '', deadline: '' }); setFormError(''); setShowForm(true) }}>New project</Button></div>} />
    {loading ? <Card><LoadingState label="Loading projects and skills…"/></Card> : error ? <Card className="p-5"><p role="alert" className="text-sm text-rose-700">{error}</p><Button className="mt-3" variant="outline" onClick={load}>Try again</Button></Card> : !projects.length ? <Card><EmptyState title="No projects yet" description="Create a project and add the skill or staffing requirements used by project-aware scheduling."/></Card> : <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{projects.map((project) => <Card key={project.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-ink">{project.name}</h2><p className="mt-1 text-xs text-muted">Project #{project.id}</p></div><button aria-label={`Edit project ${project.name}`} onClick={() => editProject(project)} className="rounded p-2 text-muted hover:bg-slate-100">Edit</button><button aria-label={`Delete project ${project.name}`} onClick={() => removeProject(project)} className="rounded p-2 text-muted hover:bg-rose-50 hover:text-rose-700"><Trash2 size={15}/></button></div><div className="mt-4 flex flex-wrap gap-2"><Badge tone={project.status?.toLowerCase() === 'active' ? 'green' : 'blue'} dot>{project.status}</Badge><Badge tone="gray"><CalendarDays size={12} className="mr-1 inline"/>{dateText(project.deadline)}</Badge></div>{project.description && <p className="mt-4 text-sm text-slate-600">{project.description}</p>}<div className="mt-5 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wide text-muted">Requirements ({project.requirements?.length || 0})</h3><Button variant="outline" onClick={() => { setFormError(''); setRequirementFor(project) }}>Add requirement</Button></div>{project.requirements?.length ? <div className="mt-3 divide-y divide-line rounded-lg border border-line">{project.requirements.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-3"><div><p className="text-sm font-medium text-ink">{item.skill?.name || item.role}</p><p className="mt-1 text-xs text-muted">{item.quantity} qualified · {item.required_hours} hours · proficiency {item.minimum_proficiency}</p></div><button aria-label={`Remove ${item.role} requirement`} onClick={() => removeRequirement(project.id, item)} className="rounded p-2 text-muted hover:text-rose-700"><Trash2 size={14}/></button></div>)}</div> : <p className="mt-3 text-xs text-muted">No project requirements have been defined.</p>}</Card>)}</div>}
    <p className="mt-4 text-xs text-muted">Values and relationships above are loaded from the backend. Priority and staffing counts are not exposed by the current project API.</p>
    {showForm && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/25" onClick={() => { setShowForm(false); setEditingProject(null) }}><form role="dialog" aria-modal="true" aria-label={editingProject ? 'Edit project' : 'Create project'} onSubmit={create} onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-md space-y-4 overflow-y-auto bg-white p-6 shadow-xl"><button type="button" aria-label="Close form" className="float-right" onClick={() => setShowForm(false)}>×</button><h2 className="text-lg font-semibold">{editingProject ? 'Edit project' : 'New project'}</h2><label className="block text-xs font-medium">Name<Input className="mt-1" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label><label className="block text-xs font-medium">Status<Select className="mt-1 w-full" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="planned">Planned</option><option value="active">Active</option><option value="completed">Completed</option></Select></label><label className="block text-xs font-medium">Deadline<Input className="mt-1" type="date" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })}/></label><label className="block text-xs font-medium">Description<textarea className="mt-1 w-full rounded-lg border border-line p-3 text-sm" rows="3" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label>{formError && <p role="alert" className="text-sm text-rose-700">{formError}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => { setShowForm(false); setEditingProject(null) }}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : editingProject ? 'Save changes' : 'Create project'}</Button></div></form></div>}
    {requirementFor && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/25" onClick={() => setRequirementFor(null)}><form role="dialog" aria-modal="true" aria-label="Add project requirement" onSubmit={addRequirement} onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-md space-y-4 bg-white p-6 shadow-xl"><button type="button" aria-label="Close form" className="float-right" onClick={() => setRequirementFor(null)}>×</button><h2 className="text-lg font-semibold">Requirement · {requirementFor.name}</h2><label className="block text-xs font-medium">Required skill (optional)<Select className="mt-1 w-full" value={requirement.skill_id} onChange={(e) => setRequirement({ ...requirement, skill_id: e.target.value })}><option value="">No specific skill</option>{skills.map((skill) => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</Select></label><label className="block text-xs font-medium">Role<Input className="mt-1" required value={requirement.role} onChange={(e) => setRequirement({ ...requirement, role: e.target.value })}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium">Qualified people<Input className="mt-1" type="number" min="1" value={requirement.quantity} onChange={(e) => setRequirement({ ...requirement, quantity: e.target.value })}/></label><label className="text-xs font-medium">Required hours<Input className="mt-1" type="number" min="0" step="0.5" value={requirement.required_hours} onChange={(e) => setRequirement({ ...requirement, required_hours: e.target.value })}/></label></div><label className="block text-xs font-medium">Minimum skill proficiency<Input className="mt-1" type="number" min="1" value={requirement.minimum_proficiency} onChange={(e) => setRequirement({ ...requirement, minimum_proficiency: e.target.value })}/></label>{formError && <p role="alert" className="text-sm text-rose-700">{formError}</p>}<Button disabled={saving}>{saving ? 'Saving…' : 'Add requirement'}</Button></form></div>}
  </>
}
