import { useMemo, useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight, Filter, MoreHorizontal, Plus, Search } from 'lucide-react'
import { Badge, Button, Card, Input, PageHeader, Select, Table } from '../components/UI'
import { departments, shifts } from '../data/mockData'
export default function Shifts() {
 const [query, setQuery] = useState(''), [department, setDepartment] = useState('All departments'), [date, setDate] = useState('All dates')
 const filtered = useMemo(() => shifts.filter((shift) => `${shift.name} ${shift.template} ${shift.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (department === 'All departments' || shift.department === department) && (date === 'All dates' || shift.date === date)), [query, department, date])
 const columns = [{ key: 'name', label: 'Shift', render: (row) => <div><p className="font-semibold text-ink">{row.name}</p><p className="mt-1 text-xs text-muted">{row.template}</p></div> }, { key: 'date', label: 'Date', render: (row) => new Date(`${row.date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) }, { key: 'time', label: 'Time' }, { key: 'department', label: 'Department' }, { key: 'required', label: 'Required staff', render: (row) => `${row.required} people` }, { key: 'skills', label: 'Required skills', render: (row) => <div className="flex gap-1.5">{row.skills.map((x) => <Badge key={x}>{x}</Badge>)}</div> }, { key: 'status', label: 'Status', render: (row) => <Badge tone={row.status === 'Covered' ? 'green' : row.status === 'Draft' ? 'gray' : 'amber'} dot>{row.status}</Badge> }, { key: 'actions', label: '', render: () => <button className="p-1.5 text-muted"><MoreHorizontal size={17}/></button> }]
 return <><PageHeader eyebrow="Planning" title="Shifts" description="Create shift templates and keep coverage requirements on track." action={<Button icon={Plus}>Add shift</Button>} /><div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-3">{[['18', 'Shifts this week', 'text-ink'], ['14', 'Fully covered', 'text-emerald-700'], ['4', 'Need attention', 'text-amber-700']].map(([value, label, color]) => <Card className="p-4" key={label}><p className={`text-2xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-xs text-muted">{label}</p></Card>)}</div><Card><div className="flex flex-wrap items-center justify-between gap-3 p-4"><div className="relative min-w-[220px] flex-1 sm:max-w-xs"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input className="pl-9" placeholder="Search shifts or skills" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="flex flex-wrap gap-2"><Select value={date} onChange={(e) => setDate(e.target.value)}><option>All dates</option>{shifts.map((s) => <option value={s.date} key={s.date}>{new Date(`${s.date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</option>)}</Select><Select value={department} onChange={(e) => setDepartment(e.target.value)}><option>All departments</option>{departments.map((d) => <option key={d}>{d}</option>)}</Select><Button variant="outline" icon={CalendarDays}>Week of 6 Oct</Button></div></div><Table columns={columns} rows={filtered} emptyMessage="No shifts match your filters."/><div className="flex items-center justify-between border-t border-line px-5 py-3 text-xs text-muted"><span>Showing {filtered.length} scheduled shifts · Mock data</span><div className="flex gap-2"><Button variant="outline"><ChevronLeft size={14}/>Previous</Button><Button variant="outline">Next<ChevronRight size={14}/></Button></div></div></Card></>
}
